version: "3.9"
services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "5001:5000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - FLASK_ENV=development
  #   restart: always
  #   networks:
  #     - monitoring

  frontend:
    build:
      context: ./nodeapp/frontend
    ports:
      - "3002:3000"
    volumes:
      - ./nodeapp/frontend:/app
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Grafana listens on port 3000 internally
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
  

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config:/etc/loki
   

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
      - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
  
volumes:
  grafana-data:
  
networks:
  monitoring:
    driver: bridge 