global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flask_backend"
    static_configs:
      - targets: ["backend:5000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
